# Generated by Django 5.0 on 2024-01-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='userid',
            field=models.CharField(max_length=100),
        ),
    ]
