# Generated by Django 5.0 on 2024-01-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_chunk_delete_testuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='data',
        ),
        migrations.AddField(
            model_name='chunk',
            name='doom',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chunk',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
