# Generated by Django 5.0 on 2024-01-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_companiessorted_userid_companiessorted_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiessorted',
            name='current_employee_estimate',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='total_employee_estimate',
            field=models.CharField(blank=True, null=True),
        ),
    ]
