# Generated by Django 5.0 on 2024-01-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_companiessorted_current_employee_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiessorted',
            name='current_employee_estimate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='total_employee_estimate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
