# Generated by Django 5.0 on 2024-01-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_companiessorted_current_employee_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiessorted',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='locality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='size_range',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companiessorted',
            name='year_founded',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
